- branch: production
  protection:
    required_status_checks:
      strict: true
    allow_force_pushes: false
    allow_deletions: false

    jobs:
      protect production:
        runs-on: macos-latest
        steps:
          - uses: actions/checkout@v2
          - name: Update branch protection
            uses: Hatzelencio/branch-protection@v0.0.0
            env:
              GITHUB_TOKEN: ${{secrets.ACCESS_TOKEN}}

- branch: master
  protection:
    required_status_checks:
      strict: true
    allow_force_pushes: false
    allow_deletions: false

    jobs:
      protect production:
        runs-on: macos-latest
        steps:
          - uses: actions/checkout@v2
          - name: Update branch protection
            uses: Hatzelencio/branch-protection@v0.0.0
            env:
              GITHUB_TOKEN: ${{secrets.ACCESS_TOKEN}}
